// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weavenest.DataAccess.Data;

#nullable disable

namespace Weavenest.DataAccess.Migrations
{
    [DbContext(typeof(WeavenestDbContext))]
    [Migration("20260316095946_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weavenest.DataAccess.Models.EmotionalState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Anger")
                        .HasColumnType("real");

                    b.Property<float>("Disgust")
                        .HasColumnType("real");

                    b.Property<float>("Fear")
                        .HasColumnType("real");

                    b.Property<float>("Happiness")
                        .HasColumnType("real");

                    b.Property<float>("Sadness")
                        .HasColumnType("real");

                    b.Property<float>("Surprise")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("EmotionalStates");
                });

            modelBuilder.Entity("Weavenest.DataAccess.Models.HumanMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.HasIndex("Timestamp");

                    b.ToTable("HumanMessages");
                });

            modelBuilder.Entity("Weavenest.DataAccess.Models.LongTermMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<float>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.5f);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmotionalContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<bool>("IsSuperseded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedMemoryIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsSuperseded");

                    b.HasIndex("LastAccessedAt");

                    b.ToTable("LongTermMemories");
                });

            modelBuilder.Entity("Weavenest.DataAccess.Models.TickLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsciousContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionalStateAfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionalStateBeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpokeContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubconsciousContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("TickLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
